sudo: required
language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq build-essential djvulibre-bin ghostscript imagemagick poppler-utils python-cairo python-djvu python-imaging python-magic python-poppler python-sqlalchemy python-xapian
install:
  - BUILD_LIB=1 pip install ssdeep
script:
  - python tests/runtests.py
